# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "qtv-conformance-runner"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[dependencies]
qtv-idfmt = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "f80496d3a334fbab933fec85c808abf351163285" }
qtv-account = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "f80496d3a334fbab933fec85c808abf351163285" }
qtv-codec = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "f80496d3a334fbab933fec85c808abf351163285" }
qtv-tx = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "f80496d3a334fbab933fec85c808abf351163285" }
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "4abe71e9fa84a6e670e6d5736d7533c3fd10a3ed" }

[profile.dev.package.qtv-crypto]
opt-level = 3

[profile.test.package.qtv-crypto]
opt-level = 3
