# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "qtv-conformance-runner"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[dependencies]
qtv-idfmt = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "ead056d2dcffc370ea35cd0446ab3921f05b4988" }
qtv-account = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "ead056d2dcffc370ea35cd0446ab3921f05b4988" }
qtv-codec = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "ead056d2dcffc370ea35cd0446ab3921f05b4988" }
qtv-tx = { git = "https://github.com/Quantova/Quantova-Chain.git", rev = "ead056d2dcffc370ea35cd0446ab3921f05b4988" }
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "e6652598dc3847189609a282128921824d55c10b" }

[profile.dev.package.qtv-crypto]
opt-level = 3

[profile.test.package.qtv-crypto]
opt-level = 3
